apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: developer-role
rules:
- apiGroups: ["", "apps"]
  resources:
    - pods
    - services
    - deployments
    - replicasets
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - delete